################################################################################
# @brief Makefile for building and running the program.
#
#        - To run and build the program, type "make" or "make all".
#        - To build the program without running, type "make build".
#        - To run the program without prior build, type "make run".
################################################################################
all: build run

################################################################################
# @brief Builds the program and creates an executable named run_print_example.
################################################################################
build:
	@g++ main.cpp -o run_print_example

################################################################################
# @brief Runs the program (by executing the executable run_print_example).
################################################################################
run:
	@./run_print_example